home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
  path('', views.index, name="index"),
]

toys/urls.py
from django.urls import path, re_path

from . import views

app_name = 'toys'

urlpatterns = [
  # item
  path('item/', views.item_index, name="item_index"),
  path('item/category/<str:category>', views.item_index, name="item_index_category"),
  path('item/sort/<int:sort>', views.item_index, name="item_index_sort"),
  path('item/create', views.item_create, name="item_create"),
  path('item/<str:name>/update', views.item_update, name="item_update"),
  path('item/<str:name>/delete', views.item_delete, name="item_delete"),

  # goods
  path('goods', views.goods_index, name="goods_index"),
  path('goods/detail/<str:goods_id>', views.goods_detail, name="goods_detail"),
  path('goods/create', views.goods_create, name="goods_create"),
  path('goods/delete/<str:goods_id>', views.goods_delete, name="goods_delete"),
  path('goods/update/<str:goods_id>', views.goods_update, name="goods_update"),
  
  # level
  path('level', views.level_index, name="level_index"),
  path('level/create', views.level_create, name="level_create"),
  path('level/update/<str:primary_key>/', views.level_update, name="level_update"),
  path('level/delete/<str:primary_key>/', views.level_delete, name="level_delete"),

  # order
  path('order', views.order_index, name="order_index"),
  path('order/create', views.order_create, name="order_create"),
  path('order/update/<str:order>', views.order_update, name="order_update"),
  path('order/update', views.order_make_update, name="order_make_update"),
  path('order/delete/<str:order>', views.order_delete, name="order_delete"),

  # chat
  path('chat/admin', views.chat_admin, name="chat_admin"),
  path('chat/member', views.chat_member, name="chat_member"),

  # delivery
  path('delivery', views.delivery_index, name="delivery_index"),
  path('delivery/create', views.delivery_create, name="delivery_create"),
  path('delivery/update/<str:primary_key>/', views.delivery_update, name="delivery_update"),
  path('delivery/delete/<str:primary_key>/', views.delivery_delete, name="delivery_delete"),

  # goods review
  path('goods/review', views.goods_review_index, name="goods_review_index"),
  path('goods/review/create', views.goods_review_create, name="goods_review_create"),
  path('goods/review/update', views.goods_review_update, name="goods_review_update"),

]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

from home.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('account/', include('account.urls')),
    path('toys/', include('toys.urls')),
]

toys/models.py
from django.db import models

# Create your models here.

toys/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from account.functions import roles_required
from toysrent.database import Database
from account.views import _set_empty_field_to_null, _required_fields_is_filled

import copy
import ast
import json

# item
@require_http_methods(["GET"])
@roles_required('any')
def item_index(request, category=None, sort=None):
  # for filter dropdown
  category_query_result = Database.executeThenFetchAll(
    'SELECT name FROM category;'
  )
  category_selection = [e[0] for e in category_query_result]

  # for table
  if sort:
    attribute = None
    order = None
    if sort in [1,2]:
      attribute = 'item_name' 
    if sort in [3,4]:
      attribute = 'category_name' 
    if sort in [1,3]:
      order = 'asc' 
    if sort in [2,4]:
      order = 'desc' 
    additional = 'order by {} {}'.format(attribute, order)
    query_result = Database.executeThenFetchAll(
    'SELECT * FROM item_category ' + additional + ';'
    )
  else:
    query_result = Database.executeThenFetchAll(
      'SELECT * FROM item_category;'
    )
  item_to_categoires = {}
  for item_name, category_name in query_result:
    if not item_name in item_to_categoires.keys():
      item_to_categoires[item_name] = [category_name]
    else:
      item_to_categoires[item_name].append(category_name)
  
  # filter item that only have category in parameter
  if category:
    keys_to_be_deleted = []
    for item, categories in item_to_categoires.items():
      if not category in categories:
        keys_to_be_deleted.append(item)

    for key in keys_to_be_deleted:
      del item_to_categoires[key]

  return render(request, 'toys/item/index.html', 
    {'data': item_to_categoires, 'category_select': category_selection,'category':category,'sort':sort})

@require_http_methods(["GET", "POST"])
@roles_required('admin')
def item_create(request):
  form = { 'error': {} }
  query_result = Database.executeThenFetchAll(
    'SELECT name FROM category;'
  )
  form['category_select'] = [e[0] for e in query_result]

  if request.method == 'GET':
    return render(request, 'toys/item/create.html', {'form': form})
  else:
    form['data'] = copy.deepcopy(request.POST)
    post_data = _set_empty_field_to_null(dict(request.POST))

    # do validation
    if not _required_fields_is_filled(post_data, ['name']):
      form['error']['name'] = 'Name required'
    if post_data['min_age'][0] > post_data['max_age'][0]:
      form['error']['max_age'] = 'Maximum age should be higher than minimum age'
    if form['error']:
      return render(request, 'toys/item/create.html', {'form': form})

    Database.executeThenCommit(
      'INSERT INTO ITEM VALUES(%s, %s, %s, %s, %s);',
      (post_data["name"][0], post_data["description"][0], post_data["min_age"][0],
          post_data["max_age"][0], post_data["material"][0])
    )
    for category in post_data["category"]:
      Database.executeThenCommit(
        'INSERT INTO ITEM_CATEGORY VALUES(%s, %s);',
        (post_data["name"][0], category)
      )

    messages.success(request, 'item created successfully')
    return HttpResponseRedirect(reverse('toys:item_index'))

@require_http_methods(["GET", "POST"])
@roles_required('admin')
def item_update(request, name):
  form = { 'error': {} }
  query_result = Database.executeThenFetchAll(
    'SELECT name FROM category;'
  )
  # get selection for category dropdown
  form['category_select'] = [e[0] for e in query_result]

  if request.method == 'GET':
    item_query_result = Database.executeThenFetchAll(
      'SELECT * FROM item where name=%s;',
      (name, )
    )
    selected_category_query_result = Database.executeThenFetchAll(
      'SELECT * FROM item_category where item_name=%s;',
      (name, )
    )

    # populate context with current item being updated
    form['data'] = {
      'name': item_query_result[0][0], 
      'description': item_query_result[0][1],
      'min_age': item_query_result[0][2],
      'max_age': item_query_result[0][3],
      'material': item_query_result[0][4],
      'category': [e[1] for e in selected_category_query_result]
    }

    return render(request, 'toys/item/update.html', {'form': form})
  else:
    form['data'] = copy.deepcopy(request.POST)
    post_data = _set_empty_field_to_null(dict(request.POST))

    # update in item table
    Database.executeThenCommit(
      'UPDATE ITEM SET name=%s, description=%s, min_age=%s, max_age=%s, material=%s \
          where name=%s;',
      (post_data["name"][0], post_data["description"][0], post_data["min_age"][0],
          post_data["max_age"][0], post_data["material"][0], name)
    )
    # update in item_category table
    previous_selected_category_query_result = Database.executeThenFetchAll(
      'SELECT category_name FROM item_category where item_name=%s;',
      (name, )
    )
    previous_selected_set = set([e[0] for e in previous_selected_category_query_result])
    new_selecteed_set = set(post_data['category'])
    # only insert and delete necessary item_category records
    for to_be_added in new_selecteed_set - previous_selected_set:
      Database.executeThenCommit(
        'INSERT INTO ITEM_CATEGORY VALUES(%s, %s);',
        (post_data["name"][0], to_be_added)
      )
    for to_be_deleted in previous_selected_set - new_selecteed_set:
      Database.executeThenCommit(
        'DELETE FROM ITEM_CATEGORY WHERE item_name=%s AND category_name=%s;',
        (post_data["name"][0], to_be_deleted)
      )
    
    messages.success(request, name + ' updated successfully')
    return HttpResponseRedirect(reverse('toys:item_index'))

@require_http_methods(["POST"])
@csrf_exempt
@roles_required('admin')
def item_delete(request, name):
  Database.executeThenCommit(
    'DELETE FROM ITEM WHERE name=%s',
    (name, )
  )
  messages.success(request, name + ' deleted successfully')
  return HttpResponseRedirect(reverse('toys:item_index'))

# goods
@roles_required("any")
def goods_index(request):
    database = Database
    res = database.executeThenFetchAll("select * from goods")
    query_category =database.executeThenFetchAll("select distinct category_name from item_category")
    if request.method =="POST":
        checked = request.POST.getlist('checked')
        request.session['checked'] = checked
        return render(request, 'toys/goods/index.html',
                      {'res': res, 'orders': checked, 'categories': query_category, 'role': request.session['role']})

    else :
        checked = request.session.get('checked')
        print(request.GET.get("category_filter"))
        print(request.GET.get("sort_by") == "" ,request.GET.get("category_filter") == "")
        print(request.GET.get("sort_by"), request.GET.get("category_filter"))

        if request.GET.get("sort_by") == None and request.GET.get("category_filter") == None:
            checked = request.session.get('checked')
            print(checked)
            return render(request, 'toys/goods/index.html',
                          {'res': res, 'orders': checked, 'categories': query_category, 'role': request.session['role']})

        if request.GET.get("sort_by") != "" and request.GET.get("category_filter") != "":
            if request.GET.get("sort_by") == 'item_name':
                res = database.executeThenFetchAll("select distinct * from goods g, item_category i where i.category_name=%s and g.item_name=i.item_name order by i.category_name,g.condition asc;",(request.GET.get("category_filter"),))
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})
            else:
                res = database.executeThenFetchAll("select distinct * from goods g, item_category i where i.category_name=%s and g.item_name=i.item_name order by i.category_name,g.condition asc;",(request.GET.get("category_filter"),))
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})


        elif request.GET.get("category_filter") != "" and request.GET.get("sort_by") == "":
            res = database.executeThenFetchAll("select distinct * from goods g,item_category i where i.category_name=%s and g.item_name=i.item_name;",(request.GET.get("category_filter"),))
            print(res)
            return render(request, 'toys/goods/index.html',
                          {'res': res, 'orders': checked, 'categories': query_category,
                           'role': request.session['role']})

        elif request.GET.get("sort_by") != "" and request.GET.get("category_filter") == "":
            print("I AM HERE")
            if request.GET.get("sort_by") == 'item_name':
                res = database.executeThenFetchAll("select distinct * from goods g order by g.item_name asc;")
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})
            else:
                res = database.executeThenFetchAll("select distinct * from goods g, item_category i where  g.item_name=i.item_name order by i.category_name,g.condition asc;")
                print(res)
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})
        else:
            checked = request.session.get('checked')
            print(checked)
            return render(request, 'toys/goods/index.html',
                          {'res': res, 'orders': checked, 'categories': query_category, 'role': request.session['role']})


@roles_required("any")

templates/toys/goods/create.html
{% extends '../../_base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/goods/create_update.css' %}">{% endblock %}


{% block content %}
    <div class="d-flex p-2 justify-content-between " id="header">
        <div class="dashboard-text">
            <p>Dashboard | <span>#{{ userid }}</span></p>
        </div>
        <div class="welcome-text">
            <p>Welcome <span>{{ username }}</span></p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12" id="addContainer">
                <form id="registrationForm" class="form-horizontal fv-form fv-form-bootstrap" method="post">
                    {% csrf_token %}
                    <h4>Goods Registration</h4>
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Goods ID</label>
                        <div class="col-xs-4">
                            <input type="text" class="form-control" name="goods_id" placeholder="Goods identification number" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Item name</label>
                        <div class="col-xs-5">
                            <select class="form-control" name="item_name">
                              {% for item in items %}
                                  <option value="{{ item.0 }}">{{ item.0 }}</option>
                              {% endfor %}
                          </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Color</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control" name="color" required/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">Photo url:</label>
                        <div class="col-xs-5">
                            <input type="text" class="form-control" name="photo" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-xs-3 control-label">Condition:</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" name="condition" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Usage length:</label>
                        <div class="col-xs-9">
                            <input type="number" min="0" class="form-control" name="usage" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label">Owner</label>
                          <select class="form-control" name="owner">
                              {% for member in members %}
                                  <option value="{{ member.0 }}">{{ member.0 }} - {{ member.1 }}</option>
                              {% endfor %}
                          </select>
                    </div>
                    <br/>
                    <h4> Goods Info</h4>
                    <div class="form-group">
                        <h6>+ Bronze level</h6>
                        <label class="col-xs-3 control-label" style="margin-left:3rem">Royalty Percentage</label>
                        <div class="col-xs-9" style="margin-left:3rem">
                            <input type="number" min="0" class="form-control" name="bronze_royalty" required/>
                        </div>
                        <label class="col-xs-3 control-label" style="margin-left:3rem">Rent Price</label>
                        <div class="col-xs-9" style="margin-left:3rem">
                            <input type="number" min="0" class="form-control" name="bronze_rent" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <h6>+ Silver level</h6>
                        <label class="col-xs-3 control-label" style="margin-left:3rem">Royalty Percentage</label>
                        <div class="col-xs-9" style="margin-left:3rem">
                            <input type="number" min="0" class="form-control" name="silver_royalty" required/>
                        </div>
                        <label class="col-xs-3 control-label" style="margin-left:3rem">Rent Price</label>
                        <div class="col-xs-9" style="margin-left:3rem">
                            <input type="number" min="0" class="form-control" name="silver_rent" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <h6>+ Gold level</h6>
                        <label class="col-xs-3 control-label" style="margin-left:3rem">Royalty Percentage</label>
                        <div class="col-xs-9" style="margin-left:3rem">
                            <input type="number" min="0" class="form-control" name="gold_royalty" required/>
                        </div>
                        <label class="col-xs-3 control-label" style="margin-left:3rem">Rent Price</label>
                        <div class="col-xs-9" style="margin-left:3rem">
                            <input type="number" min="0" class="form-control" name="gold_rent" required/>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary">
                </form>
            </div>
        </div>
        <div class="d-flex p-4 justify-content-between " id="header" style="margin-top:1rem;">
            <div class="dashboard-text">
                <p>Toysrent 2019</p>
            </div>
            <div class="welcome-text">
                <p>Pls this is so painful</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/toys/goods/detail.html
{% extends '../../_base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/goods/create_update.css' %}">{% endblock %}

{% block content %}
<!-- "718-95-807"	"Sonsing"	"Puce"	"http://dummyimage.com/237x107.jpg/5fa2dd/ffffff"	"under_repair"	80	"719-94-9942" -->
<div class="container">
  <h1>{{ obj.0.1 }}</h1>
  <table class="table">
    <tbody>
      <tr>
        <td>ID</td>
        <td>{{ obj.0.0 }}</td>
      </tr>
      <tr>
        <td>Item Name</td>
        <td>{{ obj.0.1 }}</td>
      </tr>
      <tr>
        <td>Color</td>
        <td>{{ obj.0.2 }}</td>
      </tr>
      <tr>
        <td>Photo</td>
        <td>{{ obj.0.3 }}</td>
      </tr>
      <tr>
        <td>Condition</td>
        <td>{{ obj.0.4 }}</td>
      </tr>
      <tr>
        <td>Usage Duration</td>
        <td>{{ obj.0.5 }}</td>
      </tr>
      <tr>
        <td>Renter ID</td>
        <td>{{ obj.0.6 }}</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

templates/toys/goods/index.html
{% extends '../../_base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/goods/goods_list.css' %}">{% endblock %}
{% block js %}<script src="{% static 'js/goods_pagination.js' %}"></script>{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-12 justify-content-around d-flex" style="margin:2rem 0;">
        <div class="col-md-12 d-flex" >
            <form method="GET" action="#" class="col-md-12 justify-content-space-between d-flex">
            <div class="col-md-3" >
                <label>Sort by: </label>
                <select name="sort_by">
                    <option value="">None</option>
                    <option value="category_name">Category & Condition</option>
                    <option value="item_name">Goods Name</option>
                </select>
            </div>
            <div class="col-md-3" >
                <label>Filter Category name by: </label>
                <select name="category_filter">
                    <option value=""> None </option>
                    {% for category in categories %}
                        <option value="{{ category.0 }}"> {{ category.0 }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div>
            <button class="btn btn-success"> Find </button>
        </div>
        </form>
    </div>
	<div class="row">
      <div class="table-responsive">
          <form method="post">
            {% csrf_token %}
            <table class="table table-hover" id="goods_table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Goods ID</th>
                  <th>Item Name</th>
                  <th>Color</th>
                  <th>Condition</th>
                  <th>Action</th>
                  {% if role == 'member' %}  <th>Order</th> {% endif %}
                </tr>
              </thead>
              <tbody id="myTable">
              {% for item in res  %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ item.0 }}</td>
                  <td>{{ item.1 }}</td>
                  <td>{{ item.2 }}</td>
                  <td>{{ item.4 }}</td>
                    <td>
                          <input type="hidden" name="object" value="{{ item }}">
                          <a href="{% url 'toys:goods_detail' item.0 %}" class="btn btn-primary" name="detail">See details</a>
                          {% if role == 'admin' %}
                          <a href="{% url 'toys:goods_update' item.0 %}" class="btn btn-warning" name="edit">Edit</a>
                          <button type="button" class="btn btn-danger" name="delete" data-toggle="modal" data-target="#myModal{{ item.0 }}">Delete</button>
                            <div class="modal fade" id="myModal{{ item.0 }}" role="dialog">
                            <div class="modal-dialog modal-sm">
                              <div class="modal-content">
                                <div class="modal-header">
                                   <h5>Are you sure?</h5>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure, you would like to delete item : {{ item.1 }} <i>({{ item.0 }})</i> ?</p>
                                </div>
                                <div class="modal-footer">
                                    <a href="{% url 'toys:goods_delete' item.0 %}"><button type="button" class="btn btn-danger" > Yes </button></a>
                                </div>
                              </div>
                            </div>
                          </div>
                           {% endif %}
                    </td>
                    {% if role == 'member' %}
                    <td>
                       <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" name="checked" id="order{{ item.0 }}" value="{{ item.0 }}" {% for order in orders %} {% if order == item.0 %} checked {% endif %} {% endfor %}>
                            <label class="custom-control-label" for="order{{ item.0 }}">Order</label>
                       </div>
                   </td>
                    {% endif %}
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <div class="col-md-12 justify-content-around d-flex" id="not_found">
                <p style="display:none;">Goods not found</p>
            </div>
            {% if role == 'member' %}
            <button type="submit" class="btn btn-success" name="order">Order</button>
            {% endif %}
          </form>
      </div>
      <div class="col-md-12 text-center">
      <ul class="pagination pagination-lg pager" id="myPager"></ul>
      </div>
	</div>
</div>
{% endblock %}