account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
  path('login', views.login, name="login"),
  path('logout', views.logout, name="logout"),
  path('register', views.register, name="register"), 
  path('register/member', views.register_member, name="register_member"), 
  path('register/admin', views.register_admin, name="register_admin"), 
  path('profile', views.profile, name="profile"), 
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
  path('', views.index, name="index"),
]

toys/urls.py
from django.urls import path, re_path

from . import views

app_name = 'toys'

urlpatterns = [
  # item
  path('item/', views.item_index, name="item_index"),
  path('item/category/<str:category>', views.item_index, name="item_index_category"),
  path('item/sort/<int:sort>', views.item_index, name="item_index_sort"),
  path('item/create', views.item_create, name="item_create"),
  path('item/<str:name>/update', views.item_update, name="item_update"),
  path('item/<str:name>/delete', views.item_delete, name="item_delete"),

  # goods
  path('goods', views.goods_index, name="goods_index"),
  path('goods/detail/<str:goods_id>', views.goods_detail, name="goods_detail"),
  path('goods/create', views.goods_create, name="goods_create"),
  path('goods/delete/<str:goods_id>', views.goods_delete, name="goods_delete"),
  path('goods/update/<str:goods_id>', views.goods_update, name="goods_update"),
  
  # level
  path('level', views.level_index, name="level_index"),
  path('level/create', views.level_create, name="level_create"),
  path('level/update/<str:primary_key>/', views.level_update, name="level_update"),
  path('level/delete/<str:primary_key>/', views.level_delete, name="level_delete"),

  # order
  path('order', views.order_index, name="order_index"),
  path('order/create', views.order_create, name="order_create"),
  path('order/update/<str:order>', views.order_update, name="order_update"),
  path('order/update', views.order_make_update, name="order_make_update"),
  path('order/delete/<str:order>', views.order_delete, name="order_delete"),

  # chat
  path('chat/admin', views.chat_admin, name="chat_admin"),
  path('chat/member', views.chat_member, name="chat_member"),

  # delivery
  path('delivery', views.delivery_index, name="delivery_index"),
  path('delivery/create', views.delivery_create, name="delivery_create"),
  path('delivery/update/<str:primary_key>/', views.delivery_update, name="delivery_update"),
  path('delivery/delete/<str:primary_key>/', views.delivery_delete, name="delivery_delete"),

  # goods review
  path('goods/review', views.goods_review_index, name="goods_review_index"),
  path('goods/review/create', views.goods_review_create, name="goods_review_create"),
  path('goods/review/update', views.goods_review_update, name="goods_review_update"),

]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

from home.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('account/', include('account.urls')),
    path('toys/', include('toys.urls')),
]

templates/partials/_header.html
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4 text-center">{{ title }}</h1>
  </div>
</div>

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ToysRent</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo02">
    <ul class="navbar-nav mt-2 mt-lg-0 text-dark">
      {% if request.session.id %}
      <li class="nav-item ml-2">
          <a class="nav-link btn-block" href="{% url 'account:profile' %}">{{ request.session.username }}'s Profile</a>
      </li>
        {% if request.session.role == "member" %}
        <li class="nav-item ml-2">
          <a class="nav-link btn-block" href="{% url 'toys:item_index' %}">List of Item</a>
        </li>
        <li class="nav-item ml-2">
          <a class="nav-link btn-block" href="#">List of Goods</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Order
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'toys:order_create' %}">Make Order</a>
            <a class="dropdown-item" href="{% url 'toys:order_index' %}">List of Order</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Delivery
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'toys:delivery_create' %}">Make Delivery</a>
            <a class="dropdown-item" href="{% url 'toys:delivery_index' %}">List of Deliveries</a>
          </div>
        </li>
        <li class="nav-item ml-2">
          <a class="nav-link btn-block" href="#">Chat with Admin</a>
        </li><li class="nav-item ml-2">
          <a class="nav-link btn-block" href="#">List of Goods Review</a>
        </li>
        {% elif request.session.role == "admin" %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Item
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'toys:item_create' %}">Add Item</a>
            <a class="dropdown-item" href="{% url 'toys:item_index' %}">List of Item</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Goods
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{%url 'toys:goods_create' %}">Add Goods</a>
            <a class="dropdown-item" href="{%url 'toys:goods_index' %}">List of Goods</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Level
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'toys:level_create' %}">Add Level</a>
            <a class="dropdown-item" href="{% url 'toys:level_index' %}">List of Levels</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Order
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'toys:order_create' %}">Make Order</a>
            <a class="dropdown-item" href="{% url 'toys:order_index' %}">Register List of Order</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Delivery
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'toys:delivery_create' %}">Make Delivery</a>
            <a class="dropdown-item" href="{% url 'toys:delivery_index' %}">List of Deliveries</a>
          </div>
        </li>
        <li class="nav-item ml-2">
          <a class="nav-link btn-block" href="#">Chat with User</a>
        </li>
        <li class="nav-item ml-2">
          <a class="nav-link btn-block" href="#">Register Goods Review</a>
        </li>
        {% endif %}
      <li>
        <form action="{% url 'account:logout' %}" method="POST">
          {% csrf_token %}
          <button class="nav-link" type="submit">Logout</button>
        </form>
      </li>
      {% else %}
      <!-- not logged in -->
      <li class="nav-item ml-2">
        <a class="nav-link" href="{% url 'account:login' %}">Login</a>
      </li>
      <li class="nav-item ml-2">
        <a class="nav-link" role="button" href="{% url 'account:register' %}">Register</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>