home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
  path('', views.index, name="index"),
]

toys/urls.py
from django.urls import path, re_path

from . import views

app_name = 'toys'

urlpatterns = [
  # item
  path('item/', views.item_index, name="item_index"),
  path('item/category/<str:category>', views.item_index, name="item_index_category"),
  path('item/sort/<int:sort>', views.item_index, name="item_index_sort"),
  path('item/create', views.item_create, name="item_create"),
  path('item/<str:name>/update', views.item_update, name="item_update"),
  path('item/<str:name>/delete', views.item_delete, name="item_delete"),

  # goods
  path('goods', views.goods_index, name="goods_index"),
  path('goods/detail/<str:goods_id>', views.goods_detail, name="goods_detail"),
  path('goods/create', views.goods_create, name="goods_create"),
  path('goods/delete/<str:goods_id>', views.goods_delete, name="goods_delete"),
  path('goods/update/<str:goods_id>', views.goods_update, name="goods_update"),
  
  # level
  path('level', views.level_index, name="level_index"),
  path('level/create', views.level_create, name="level_create"),
  path('level/update/<str:primary_key>/', views.level_update, name="level_update"),
  path('level/delete/<str:primary_key>/', views.level_delete, name="level_delete"),

  # order
  path('order', views.order_index, name="order_index"),
  path('order/create', views.order_create, name="order_create"),
  path('order/update/<str:order>', views.order_update, name="order_update"),
  path('order/update', views.order_make_update, name="order_make_update"),
  path('order/delete/<str:order>', views.order_delete, name="order_delete"),

  # chat
  path('chat/admin', views.chat_admin, name="chat_admin"),
  path('chat/member', views.chat_member, name="chat_member"),

  # delivery
  path('delivery', views.delivery_index, name="delivery_index"),
  path('delivery/create', views.delivery_create, name="delivery_create"),
  path('delivery/update/<str:primary_key>/', views.delivery_update, name="delivery_update"),
  path('delivery/delete/<str:primary_key>/', views.delivery_delete, name="delivery_delete"),

  # goods review
  path('goods/review', views.goods_review_index, name="goods_review_index"),
  path('goods/review/create', views.goods_review_create, name="goods_review_create"),
  path('goods/review/update', views.goods_review_update, name="goods_review_update"),

]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include

from home.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('account/', include('account.urls')),
    path('toys/', include('toys.urls')),
]

toys/models.py
from django.db import models

# Create your models here.

toys/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from account.functions import roles_required
from toysrent.database import Database
from account.views import _set_empty_field_to_null, _required_fields_is_filled

import copy
import ast
import json

# item
@require_http_methods(["GET"])
@roles_required('any')
def item_index(request, category=None, sort=None):
  # for filter dropdown
  category_query_result = Database.executeThenFetchAll(
    'SELECT name FROM category;'
  )
  category_selection = [e[0] for e in category_query_result]

  # for table
  if sort:
    attribute = None
    order = None
    if sort in [1,2]:
      attribute = 'item_name' 
    if sort in [3,4]:
      attribute = 'category_name' 
    if sort in [1,3]:
      order = 'asc' 
    if sort in [2,4]:
      order = 'desc' 
    additional = 'order by {} {}'.format(attribute, order)
    query_result = Database.executeThenFetchAll(
    'SELECT * FROM item_category ' + additional + ';'
    )
  else:
    query_result = Database.executeThenFetchAll(
      'SELECT * FROM item_category;'
    )
  item_to_categoires = {}
  for item_name, category_name in query_result:
    if not item_name in item_to_categoires.keys():
      item_to_categoires[item_name] = [category_name]
    else:
      item_to_categoires[item_name].append(category_name)
  
  # filter item that only have category in parameter
  if category:
    keys_to_be_deleted = []
    for item, categories in item_to_categoires.items():
      if not category in categories:
        keys_to_be_deleted.append(item)

    for key in keys_to_be_deleted:
      del item_to_categoires[key]

  return render(request, 'toys/item/index.html', 
    {'data': item_to_categoires, 'category_select': category_selection,'category':category,'sort':sort})

@require_http_methods(["GET", "POST"])
@roles_required('admin')
def item_create(request):
  form = { 'error': {} }
  query_result = Database.executeThenFetchAll(
    'SELECT name FROM category;'
  )
  form['category_select'] = [e[0] for e in query_result]

  if request.method == 'GET':
    return render(request, 'toys/item/create.html', {'form': form})
  else:
    form['data'] = copy.deepcopy(request.POST)
    post_data = _set_empty_field_to_null(dict(request.POST))

    # do validation
    if not _required_fields_is_filled(post_data, ['name']):
      form['error']['name'] = 'Name required'
    if post_data['min_age'][0] > post_data['max_age'][0]:
      form['error']['max_age'] = 'Maximum age should be higher than minimum age'
    if form['error']:
      return render(request, 'toys/item/create.html', {'form': form})

    Database.executeThenCommit(
      'INSERT INTO ITEM VALUES(%s, %s, %s, %s, %s);',
      (post_data["name"][0], post_data["description"][0], post_data["min_age"][0],
          post_data["max_age"][0], post_data["material"][0])
    )
    for category in post_data["category"]:
      Database.executeThenCommit(
        'INSERT INTO ITEM_CATEGORY VALUES(%s, %s);',
        (post_data["name"][0], category)
      )

    messages.success(request, 'item created successfully')
    return HttpResponseRedirect(reverse('toys:item_index'))

@require_http_methods(["GET", "POST"])
@roles_required('admin')
def item_update(request, name):
  form = { 'error': {} }
  query_result = Database.executeThenFetchAll(
    'SELECT name FROM category;'
  )
  # get selection for category dropdown
  form['category_select'] = [e[0] for e in query_result]

  if request.method == 'GET':
    item_query_result = Database.executeThenFetchAll(
      'SELECT * FROM item where name=%s;',
      (name, )
    )
    selected_category_query_result = Database.executeThenFetchAll(
      'SELECT * FROM item_category where item_name=%s;',
      (name, )
    )

    # populate context with current item being updated
    form['data'] = {
      'name': item_query_result[0][0], 
      'description': item_query_result[0][1],
      'min_age': item_query_result[0][2],
      'max_age': item_query_result[0][3],
      'material': item_query_result[0][4],
      'category': [e[1] for e in selected_category_query_result]
    }

    return render(request, 'toys/item/update.html', {'form': form})
  else:
    form['data'] = copy.deepcopy(request.POST)
    post_data = _set_empty_field_to_null(dict(request.POST))

    # update in item table
    Database.executeThenCommit(
      'UPDATE ITEM SET name=%s, description=%s, min_age=%s, max_age=%s, material=%s \
          where name=%s;',
      (post_data["name"][0], post_data["description"][0], post_data["min_age"][0],
          post_data["max_age"][0], post_data["material"][0], name)
    )
    # update in item_category table
    previous_selected_category_query_result = Database.executeThenFetchAll(
      'SELECT category_name FROM item_category where item_name=%s;',
      (name, )
    )
    previous_selected_set = set([e[0] for e in previous_selected_category_query_result])
    new_selecteed_set = set(post_data['category'])
    # only insert and delete necessary item_category records
    for to_be_added in new_selecteed_set - previous_selected_set:
      Database.executeThenCommit(
        'INSERT INTO ITEM_CATEGORY VALUES(%s, %s);',
        (post_data["name"][0], to_be_added)
      )
    for to_be_deleted in previous_selected_set - new_selecteed_set:
      Database.executeThenCommit(
        'DELETE FROM ITEM_CATEGORY WHERE item_name=%s AND category_name=%s;',
        (post_data["name"][0], to_be_deleted)
      )
    
    messages.success(request, name + ' updated successfully')
    return HttpResponseRedirect(reverse('toys:item_index'))

@require_http_methods(["POST"])
@csrf_exempt
@roles_required('admin')
def item_delete(request, name):
  Database.executeThenCommit(
    'DELETE FROM ITEM WHERE name=%s',
    (name, )
  )
  messages.success(request, name + ' deleted successfully')
  return HttpResponseRedirect(reverse('toys:item_index'))

# goods
@roles_required("any")
def goods_index(request):
    database = Database
    res = database.executeThenFetchAll("select * from goods")
    query_category =database.executeThenFetchAll("select distinct category_name from item_category")
    if request.method =="POST":
        checked = request.POST.getlist('checked')
        request.session['checked'] = checked
        return render(request, 'toys/goods/index.html',
                      {'res': res, 'orders': checked, 'categories': query_category, 'role': request.session['role']})

    else :
        checked = request.session.get('checked')
        print(request.GET.get("category_filter"))
        print(request.GET.get("sort_by") == "" ,request.GET.get("category_filter") == "")
        print(request.GET.get("sort_by"), request.GET.get("category_filter"))

        if request.GET.get("sort_by") == None and request.GET.get("category_filter") == None:
            checked = request.session.get('checked')
            print(checked)
            return render(request, 'toys/goods/index.html',
                          {'res': res, 'orders': checked, 'categories': query_category, 'role': request.session['role']})

        if request.GET.get("sort_by") != "" and request.GET.get("category_filter") != "":
            if request.GET.get("sort_by") == 'item_name':
                res = database.executeThenFetchAll("select distinct * from goods g, item_category i where i.category_name=%s and g.item_name=i.item_name order by i.category_name,g.condition asc;",(request.GET.get("category_filter"),))
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})
            else:
                res = database.executeThenFetchAll("select distinct * from goods g, item_category i where i.category_name=%s and g.item_name=i.item_name order by i.category_name,g.condition asc;",(request.GET.get("category_filter"),))
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})


        elif request.GET.get("category_filter") != "" and request.GET.get("sort_by") == "":
            res = database.executeThenFetchAll("select distinct * from goods g,item_category i where i.category_name=%s and g.item_name=i.item_name;",(request.GET.get("category_filter"),))
            print(res)
            return render(request, 'toys/goods/index.html',
                          {'res': res, 'orders': checked, 'categories': query_category,
                           'role': request.session['role']})

        elif request.GET.get("sort_by") != "" and request.GET.get("category_filter") == "":
            print("I AM HERE")
            if request.GET.get("sort_by") == 'item_name':
                res = database.executeThenFetchAll("select distinct * from goods g order by g.item_name asc;")
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})
            else:
                res = database.executeThenFetchAll("select distinct * from goods g, item_category i where  g.item_name=i.item_name order by i.category_name,g.condition asc;")
                print(res)
                return render(request, 'toys/goods/index.html',
                              {'res': res, 'orders': checked, 'categories': query_category,'role':request.session['role']})
        else:
            checked = request.session.get('checked')
            print(checked)
            return render(request, 'toys/goods/index.html',
                          {'res': res, 'orders': checked, 'categories': query_category, 'role': request.session['role']})


@roles_required("any")

templates/toys/item/create.html
{% extends '../../_base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block js %}
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
{% endblock %}

{% block content %}
{% include '../../partials/_header.html' with title="Item Registration Form" %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-md-6">
      <form action="{% url 'toys:item_create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" name="name" id="name" 
              class="form-control {% if form.error.name %}is-invalid{% endif %}"
              placeholder="Name" value="{{form.data.name}}" required autofocus>
          <div class="invalid-feedback">{{form.error.name}}</div>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <input type="description" name="description" id="description" 
              class="form-control {% if form.error.description %}is-invalid{% endif %}" 
              placeholder="description"  value="{{form.data.description}}">
          <div class="invalid-feedback">{{form.error.description}}</div>
        </div>
        <div class="form-group">
            <label>Age</label>
            <input type="number" name="min_age" id="min_age" min="0" max="100" 
                class="form-control {% if form.error.min_age %}is-invalid{% endif %}" 
                placeholder="min_age"  value="{{form.data.min_age}}" 
                style="width: 20%; display: inline-block;" required>
            -
            <input type="number" name="max_age" id="max_age" min="0" max="100" 
                class="form-control {% if form.error.max_age %}is-invalid{% endif %}" 
                placeholder="max_age"  value="{{form.data.max_age}}" 
                style="width: 20%; display: inline-block;" required>
            <div class="invalid-feedback">{{form.error.min_age}}</div>
            <div class="invalid-feedback">{{form.error.max_age}}</div>
          </div>
        <div class="form-group">
          <label for="material">Material</label>
          <input type="material" name="material" id="material" 
              class="form-control {% if form.error.material %}is-invalid{% endif %}" 
              placeholder="material"  value="{{form.data.material}}">
          <div class="invalid-feedback">{{form.error.material}}</div>
        </div>
        <div class="form-group">
          <label for="category">Category</label>
          <div class="form-row align-items-center">
            <div class="col-auto my-1">
              <select id="category" name="category" multiple class="selectpicker 
                  {% if form.error.material %}is-invalid{% endif %}">
                {% for category in form.category_select %}
                <option value="{{category}}">{{category}}</option>
                {% endfor %}
              </select>
              <div class="invalid-feedback">{{form.error.material}}</div>
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/toys/item/index.html
{% extends '../../_base.html' %} 
{% load static %}

{% block js %}<script src="{% static 'js/goods_pagination.js' %}"></script>{% endblock %}

{% block content %}
{% include '../../partials/_header.html' with title="Item List" %}
<div class="container">
  <div class="dropdown" style="display: inline-block">
    <button class="btn btn-secondary dropdown-toggle" type="button" 
        id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Filter Category
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      {% for c in category_select %}
      <a class="dropdown-item" href="{% url 'toys:item_index_category' c %}">{{ c }}</a>
      {% endfor %}
    </div>
  </div>
  <div class="dropdown" style="display: inline-block">
    <button class="btn btn-secondary dropdown-toggle" type="button" 
        id="dropdownSorting" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sorting
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownSorting">
      <a class="dropdown-item" href="{% url 'toys:item_index_sort' 1 %}">Name ASC</a>
      <a class="dropdown-item" href="{% url 'toys:item_index_sort' 2 %}">Name DESC</a>
      <a class="dropdown-item" href="{% url 'toys:item_index_sort' 3 %}">Category ASC</a>
      <a class="dropdown-item" href="{% url 'toys:item_index_sort' 4 %}">Category DESC</a>
    </div>
  </div>
  {% if category %}
  <h5>filtered by category {{category}}</h5>
  {% endif %}
  {% if sort %}
  <h5>sorted by 
    {% if sort == 1 %}
    Name ASC
    {% elif sort == 2 %}
    Name Desc
    {% elif sort == 3 %}
    Category ASC
    {% elif sort == 4 %}
    Category DESC
    {% endif %}
  </h5>
  {% endif %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Item Name</th>
        <th scope="col">Category</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody id="myTable">
      {% for item_name, item_categories in data.items %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item_name }}</td>
        <td>{{ item_categories|join:", " }}</td>
        <td>
          <a type="button" class="btn btn-primary">See goods</a>
          {% if request.session.role == 'admin' %}
          <a href="{% url 'toys:item_update' item_name %}" type="button" class="btn btn-warning">Update</a>
          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{ item_name }}">
            Delete
          </button>
          <div class="modal fade" id="exampleModal{{ item_name }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{ item_name }}" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <form action="{% url 'toys:item_delete' item_name %}" method="POST">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirm delete {{ item_name }}?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <a type="button" class="btn btn-primary">Add goods</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <nav aria-label="Page navigation example">
    <ul class="pagination pagination-lg pager" id="myPager"></ul>
  </nav>
</div>
{% endblock %}

templates/toys/item/update.html
{% extends '../../_base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block js %}
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
<!-- selects current item category -->
<script>
$('.selectpicker').selectpicker('val', {{ form.data.category|safe }});
</script>
{% endblock %}

{% block content %}
{% include '../../partials/_header.html' with title="Update Item Form" %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-md-6">
      <form action="{% url 'toys:item_update' form.data.name %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" name="name" id="name" 
              class="form-control {% if form.error.name %}is-invalid{% endif %}"
              placeholder="Name" value="{{form.data.name}}" required autofocus>
          <div class="invalid-feedback">{{form.error.name}}</div>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <input type="description" name="description" id="description" 
              class="form-control {% if form.error.description %}is-invalid{% endif %}" 
              placeholder="description"  value="{{form.data.description}}">
          <div class="invalid-feedback">{{form.error.description}}</div>
        </div>
        <div class="form-group">
            <label>Age</label>
            <input type="number" name="min_age" id="min_age" min="0" max="100" 
                class="form-control {% if form.error.min_age %}is-invalid{% endif %}" 
                placeholder="min_age"  value="{{form.data.min_age}}" 
                style="width: 20%; display: inline-block;" required>
            -
            <input type="number" name="max_age" id="max_age" min="0" max="100" 
                class="form-control {% if form.error.max_age %}is-invalid{% endif %}" 
                placeholder="max_age"  value="{{form.data.max_age}}" 
                style="width: 20%; display: inline-block;" required>
            <div class="invalid-feedback">{{form.error.min_age}}</div>
            <div class="invalid-feedback">{{form.error.max_age}}</div>
          </div>
        <div class="form-group">
          <label for="material">Material</label>
          <input type="material" name="material" id="material" 
              class="form-control {% if form.error.material %}is-invalid{% endif %}" 
              placeholder="material"  value="{{form.data.material}}">
          <div class="invalid-feedback">{{form.error.material}}</div>
        </div>
        <div class="form-group">
          <label for="category">Category</label>
          <div class="form-row align-items-center">
            <div class="col-auto my-1">
              <select id="category" name="category" multiple class="selectpicker 
                  {% if form.error.material %}is-invalid{% endif %}">
                {% for category in form.category_select %}
                <option value="{{category}}">{{category}}</option>
                {% endfor %}
              </select>
              <div class="invalid-feedback">{{form.error.material}}</div>
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}